apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-debd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-debd@sha256:5ccae5c458a543261fe4d94773bc6be55bb1a82082a7bda90f07f4d844a2a888
        name: my-nodejs
        resources: {}
status: {}
